spring:
  datasource:
    url: jdbc:mysql://localhost/trazarcovid?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: usuario
    password: contraseña

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always