spring:
  datasource:
    url: jdbc:mysql://34.66.173.4/trazarcovid?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: milanesa

  mvc:
    format:
      date-time: iso

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
#    hibernate:
#      ddl-auto: update

server:
  error:
    include-message: always
